services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=hi,en,mr,ta,te,kn,ml,gu,pa,bn,ur,ar,fr,ja
    restart: unless-stopped
